services:
  - type: web
    name: recoverai-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
      - key: DEMO_MODE
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: recoverai-db
          property: connectionString

databases:
  - name: recoverai-db
    plan: free
    region: oregon
