"""PolicyProposal SQLAlchemy ORM model for Self-Learning Policy Optimizer."""

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Optional, Dict, Any, List
from sqlalchemy import String, Numeric, Integer, Float, DateTime, JSON, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class PolicyProposal(Base):
    """Policy improvement proposal generated by the Self-Learning Policy Optimizer."""

    __tablename__ = "policy_proposals"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    proposal_id: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        index=True,
        nullable=False,
    )
    policy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("policies.id", ondelete="CASCADE"),
        nullable=False,
    )
    parameter_name: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )
    current_value: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    proposed_value: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    policy_version_before: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
    )
    policy_version_after: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
    )
    status: Mapped[str] = mapped_column(
        String(30),
        default="PENDING_REVIEW",
        nullable=False,
        index=True,
    )  # "PENDING_REVIEW", "APPROVED", "REJECTED", "ACTIVATED", "ROLLED_BACK", "STALE"

    confidence_score: Mapped[float] = mapped_column(
        Float,
        default=0.85,
        nullable=False,
    )
    observations_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
    )
    affected_transactions: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
    )

    # Projected Impact Deltas (Counterfactual Simulation Output)
    projected_recovery_delta: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False,
    )
    projected_cost_delta: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        default=Decimal("0.00"),
        nullable=False,
    )
    projected_net_revenue_delta: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        default=Decimal("0.00"),
        nullable=False,
    )
    projected_customer_friction_delta: Mapped[float] = mapped_column(
        Float,
        default=0.0,
        nullable=False,
    )

    # Explanatory & AI Advisor Telemetry (Purely Advisory)
    ai_summary: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
    )
    ai_rationale: Mapped[Optional[str]] = mapped_column(
        String(2000),
        nullable=True,
    )
    ai_risk_factors: Mapped[Optional[List[str]]] = mapped_column(
        JSONB().with_variant(JSON(), "sqlite"),
        nullable=True,
    )
    why_not_alternatives: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSONB().with_variant(JSON(), "sqlite"),
        nullable=True,
    )
    safety_assessment: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSONB().with_variant(JSON(), "sqlite"),
        nullable=True,
    )

    # Human Review & Governance
    reviewed_by: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
    )
    review_reason: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
    )
    reviewed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    activated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationships
    policy = relationship("Policy", backref="proposals")
