"""add policy proposals and versioning

Revision ID: 3233e44f08f1
Revises: 644043a903ea
Create Date: 2026-08-30 00:23:22.239631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3233e44f08f1'
down_revision: Union[str, None] = '644043a903ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('parameter_name', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.String(length=100), nullable=False),
    sa.Column('proposed_value', sa.String(length=100), nullable=False),
    sa.Column('policy_version_before', sa.Integer(), nullable=False),
    sa.Column('policy_version_after', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('observations_count', sa.Integer(), nullable=False),
    sa.Column('affected_transactions', sa.Integer(), nullable=False),
    sa.Column('projected_recovery_delta', sa.Float(), nullable=False),
    sa.Column('projected_cost_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('projected_net_revenue_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('projected_customer_friction_delta', sa.Float(), nullable=False),
    sa.Column('ai_summary', sa.String(length=500), nullable=True),
    sa.Column('ai_rationale', sa.String(length=2000), nullable=True),
    sa.Column('ai_risk_factors', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('why_not_alternatives', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('safety_assessment', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_proposals_parameter_name'), 'policy_proposals', ['parameter_name'], unique=False)
    op.create_index(op.f('ix_policy_proposals_proposal_id'), 'policy_proposals', ['proposal_id'], unique=True)
    op.create_index(op.f('ix_policy_proposals_status'), 'policy_proposals', ['status'], unique=False)
    op.add_column('policies', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('policies', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'description')
    op.drop_column('policies', 'version')
    op.drop_index(op.f('ix_policy_proposals_status'), table_name='policy_proposals')
    op.drop_index(op.f('ix_policy_proposals_proposal_id'), table_name='policy_proposals')
    op.drop_index(op.f('ix_policy_proposals_parameter_name'), table_name='policy_proposals')
    op.drop_table('policy_proposals')
    # ### end Alembic commands ###
