"""tier2_models_and_fields

Revision ID: 644043a903ea
Revises: 69f16cc8654f
Create Date: 2026-08-26 21:34:49.019619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '644043a903ea'
down_revision: Union[str, None] = '69f16cc8654f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_code'), 'merchants', ['code'], unique=True)
    op.create_index(op.f('ix_merchants_external_id'), 'merchants', ['external_id'], unique=True)
    op.create_table('payment_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('affected_gateway', sa.String(length=100), nullable=False),
    sa.Column('affected_payment_method', sa.String(length=100), nullable=True),
    sa.Column('failure_types', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('estimated_revenue_impact', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('root_cause_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence_list', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_incidents_affected_gateway'), 'payment_incidents', ['affected_gateway'], unique=False)
    op.create_index(op.f('ix_payment_incidents_incident_code'), 'payment_incidents', ['incident_code'], unique=True)
    op.create_index(op.f('ix_payment_incidents_severity'), 'payment_incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_payment_incidents_status'), 'payment_incidents', ['status'], unique=False)
    op.create_table('recovery_experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_a', sa.String(length=100), nullable=False),
    sa.Column('strategy_b', sa.String(length=100), nullable=False),
    sa.Column('traffic_percentage', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_experiments_status'), 'recovery_experiments', ['status'], unique=False)
    op.create_table('recovery_experiment_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('revenue_risk_id', sa.UUID(), nullable=False),
    sa.Column('assigned_strategy', sa.String(length=100), nullable=False),
    sa.Column('variant', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['recovery_experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revenue_risk_id'], ['revenue_risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_experiment_assignments_experiment_id'), 'recovery_experiment_assignments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_recovery_experiment_assignments_revenue_risk_id'), 'recovery_experiment_assignments', ['revenue_risk_id'], unique=False)
    op.add_column('customers', sa.Column('merchant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'merchants', ['merchant_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('gateway_name', sa.String(length=100), server_default='Gateway A', nullable=False))
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=50), server_default='credit_card', nullable=False))
    op.create_index(op.f('ix_transactions_gateway_name'), 'transactions', ['gateway_name'], unique=False)
    op.create_index(op.f('ix_transactions_payment_method'), 'transactions', ['payment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_payment_method'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gateway_name'), table_name='transactions')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'gateway_name')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_column('customers', 'merchant_id')
    op.drop_index(op.f('ix_recovery_experiment_assignments_revenue_risk_id'), table_name='recovery_experiment_assignments')
    op.drop_index(op.f('ix_recovery_experiment_assignments_experiment_id'), table_name='recovery_experiment_assignments')
    op.drop_table('recovery_experiment_assignments')
    op.drop_index(op.f('ix_recovery_experiments_status'), table_name='recovery_experiments')
    op.drop_table('recovery_experiments')
    op.drop_index(op.f('ix_payment_incidents_status'), table_name='payment_incidents')
    op.drop_index(op.f('ix_payment_incidents_severity'), table_name='payment_incidents')
    op.drop_index(op.f('ix_payment_incidents_incident_code'), table_name='payment_incidents')
    op.drop_index(op.f('ix_payment_incidents_affected_gateway'), table_name='payment_incidents')
    op.drop_table('payment_incidents')
    op.drop_index(op.f('ix_merchants_external_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_code'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
