"""initial_schema

Revision ID: 69f16cc8654f
Revises: 
Create Date: 2026-08-24 21:47:43.158958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69f16cc8654f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('payment_method_type', sa.String(length=50), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_expiry', sa.String(length=7), nullable=True),
    sa.Column('is_opted_out', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=True)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('max_auto_recovery_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowed_actions', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_rule_code'), 'policies', ['rule_code'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('gateway_payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_failure_code'), 'transactions', ['failure_code'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_table('revenue_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('detected_failure_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_risks_created_at'), 'revenue_risks', ['created_at'], unique=False)
    op.create_index(op.f('ix_revenue_risks_customer_id'), 'revenue_risks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_revenue_risks_detected_failure_type'), 'revenue_risks', ['detected_failure_type'], unique=False)
    op.create_index(op.f('ix_revenue_risks_status'), 'revenue_risks', ['status'], unique=False)
    op.create_index(op.f('ix_revenue_risks_transaction_id'), 'revenue_risks', ['transaction_id'], unique=True)
    op.create_table('recovery_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revenue_risk_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('proposed_action', sa.String(length=50), nullable=False),
    sa.Column('diagnosis_category', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('policy_approved', sa.Boolean(), nullable=False),
    sa.Column('policy_rejection_reason', sa.Text(), nullable=True),
    sa.Column('executed_action', sa.String(length=50), nullable=True),
    sa.Column('execution_channel', sa.String(length=50), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=False),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outcome_details', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['revenue_risk_id'], ['revenue_risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_attempts_revenue_risk_id'), 'recovery_attempts', ['revenue_risk_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revenue_risk_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('recovery_attempt_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=50), nullable=True),
    sa.Column('policy_decision', sa.String(length=50), nullable=True),
    sa.Column('executed_action', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stop_reason', sa.String(length=100), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('decision_payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_attempt_id'], ['recovery_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revenue_risk_id'], ['revenue_risks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_customer_id'), 'audit_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_recovery_attempt_id'), 'audit_logs', ['recovery_attempt_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_revenue_risk_id'), 'audit_logs', ['revenue_risk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_revenue_risk_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_recovery_attempt_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_customer_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_recovery_attempts_revenue_risk_id'), table_name='recovery_attempts')
    op.drop_table('recovery_attempts')
    op.drop_index(op.f('ix_revenue_risks_transaction_id'), table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_status'), table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_detected_failure_type'), table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_customer_id'), table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_created_at'), table_name='revenue_risks')
    op.drop_table('revenue_risks')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_failure_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_policies_rule_code'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
